### ISSUE TITLE
Typos in the Wiki of Single subject pipeline for intracranial EEG

### ISSUE THREAD

**Issue by XiaoyuZeng** [kevmtan/electroCUDA#2]
Hi Kevin,
I went through the Wiki of Single subject pipeline for intracranial EEG. 
Based on your later reference to the steps in Source separation in the Optional steps for gamma or HFB bands, I guess those steps in the Source separation should be named '7-12' instead of the current '6-11'.
It seems I could not submit a pull request in the Wiki, thus I'm opening an issue to remind you of that. : )

Best,
Xiaoyu

**Comment by kevmtan** [comment]
thanks, fixed! the wiki (and code) is very incomplete and will undergo many changes
